### ISSUE TITLE
Licensing information of the Project

### ISSUE THREAD

**Issue by vyasashish** [tokudu/AndroidPushNotificationsDemo#3]
Hi Anton,
Thanks for such a simple example for android MQTT client.Having said that I would request you to kindly let us know about the licencing of the project as it is not mentioned in the project directory.

Thanks and Regards
Ashish Vyas

**Comment by tokudu** [comment]
Apache license. Enjoy! I will update the repo.

**Comment by vyasashish** [comment]
Thanks
